apiVersion: v1
kind: Service
metadata:
  name: nodejs-service-lb
spec:
  type: LoadBalancer
  selector:
    app: nodejs-app
  ports:
  - protocol: TCP
    port: 3200 # ClusterIP Port, Will Automatically Created
    targetPort: 3000 # Container Port, Inside a Pod
    nodePort: 30008 # range nodeport 30000 - 32767