apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels: 
    app: nodejs-app
spec:
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs
        image: bayusantiko/flou:tagVersion
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
